Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Blogs.urls')),
    path('users/', include('users.urls'))
]

Blogs/urls.py
from django.urls import path
from . import views

app_name = 'Blogs'

urlpatterns = [
    path('', views.index, name='index'),
    path('new_blog/', views.new_blog, name='new_blog'),
    path('edit_blog/<int:blog_id>/', views.edit_blog, name='edit_blog'),
    path('edit_allblogs', views.edit_all_blogs, name='edit_all_blogs')
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register')
]

Blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class BlogPost(models.Model):
    title = models.CharField(max_length=50)
    text = models.TextField(max_length=400)
    date_added = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

Blogs/forms.py
from django import forms
from .models import BlogPost


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'title': 'Your event', 'text': 'About what'}
        widgets = {
            'title': forms.Textarea(attrs={'cols': 40, 'rows': 0}),
            'text': forms.Textarea(attrs={'cols': 80, 'rows': 30})
        }

Blogs/views.py
from django.shortcuts import render, redirect
from .models import BlogPost
from .forms import BlogPostForm
from django.contrib.auth.decorators import login_required
from django.http import Http404


def check_blog_owner(request, blog):
    """Protect from edit foreign blog"""
    if blog.user != request.user:
        raise Http404


def index(request):
    """Main page"""
    blogs = BlogPost.objects.order_by('-date_added')
    context = {'blogs': blogs, 'request': request}
    return render(request, 'Blogs/index.html', context)


@login_required
def new_blog(request):
    """Redirect to create page with form"""
    if request.method != 'POST':
        form = BlogPostForm()
    else:
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            new_personal_blog = form.save(commit=False)
            new_personal_blog.user = request.user
            new_personal_blog.save()
            return redirect('Blogs:index')
    context = {'form': form}
    return render(request, 'Blogs/new_blog.html', context)


@login_required
def edit_all_blogs(request):
    """Redirect to user blogs page"""
    blogs = BlogPost.objects.filter(user_id=request.user).order_by('-date_added')
    context = {'blogs': blogs}
    return render(request, 'Blogs/edit_all_blogs.html', context)


@login_required
def edit_blog(request, blog_id):
    """Redirect to user blog page with edit form"""
    blog = BlogPost.objects.get(id=blog_id)
    check_blog_owner(request, blog)
    if request.method != 'POST':
        form = BlogPostForm(instance=blog)
    else:
        form = BlogPostForm(instance=blog, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('Blogs:index')
    context = {'blog': blog, 'form': form}
    return render(request, 'Blogs/edit_blog.html', context)

users/views.py
import requests
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('Blogs:index')
    context = {'form': form}
    return render(request, 'registration/register.html', context)

Blogs/templates/Blogs/edit_all_blogs.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="{% static 'css/indexCSS.css' %}" type="text/css">
  <title>Your Blogs</title>
</head>
<body>
  <a href="{% url 'users:logout' %}">Log out</a>
  {% for blog in blogs %}
    <div class="Blog">

      <h3>{{ blog.title }}</h3>
      <div class="Text">
        <p> {{ blog.text }} </p>
      </div>
      <div class="Info">
        <p>{{ blog.date_added }}
          {% if user.is_authenticated %}
          <a href="{% url 'Blogs:edit_blog' blog.id %}">Edit blog</a>
          {% endif %}
        </p>
      </div>
    </div>
  {% endfor %}
</body>
</html>

Blogs/templates/Blogs/edit_blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <link rel="stylesheet" href="{% static 'css/editCSS.css' %}" type="text/css">
</head>
<body>
  <div class="Edit">
    <h2>Edit blog</h2>
    <div class="Edit__Form">
      <form action="{% url 'Blogs:edit_blog' blog.id %}" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button name="submit">Save changes</button>
      </form>
    </div>
  </div>
</body>
</html>

Blogs/templates/Blogs/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>My Blog</title>
  <link rel="stylesheet" href="{% static 'css/indexCSS.css' %}" type="text/css">
  <link rel="shortcut icon" href="/css/pexels-mihis-alex-21008.jpg" type="image/jpg">
</head>

<body>

  {% if user.is_authenticated %}

    <h2>Hello,{{ user.username }}
      <a href="{% url 'Blogs:new_blog' %}" class="NewLink">New Blog</a> -
      <a class="logoutL" href="{% url 'Blogs:edit_all_blogs' %}">Edit my Blogs</a>
      <a class="logoutR" href="{% url 'users:logout' %} ">Log out</a>
    </h2>

  {% else %}
      <h2>
        <a href="{% url 'users:login' %}">Log in</a>
        <a href="{% url 'users:register' %}">Register</a>
      </h2>
  {% endif %}


  {% for blog in blogs %}
    <div class="Blog">

      <h3>{{ blog.title }}</h3>
      <div class="Text">
        <p> {{ blog.text }} </p>
      </div>
      <div class="Info">
        <p>{{ blog.date_added }}
{#          {% if user.is_authenticated %}#}
{#          <a href="{% url 'Blogs:edit_blog' blog.id %}">Edit blog</a>#}
{#          {% endif %}#}
        </p>
      </div>
    </div>
  {% endfor %}


</body>

</html>

Blogs/templates/Blogs/new_blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>Add a new blog</h2>
    <form action="{% url 'Blogs:new_blog'%}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add new blog</button>
    </form>
</body>
</html>